name: CI/CD for Georeach - Deploy Blazor and API to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.x'
          include-prerelease: true

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      # Publish API to a subfolder within a shared output directory
      - name: Publish API
        run: dotnet publish GeoreachAPI/GeoreachAPI.csproj -c Release -o deployment_output/api

      # Publish Blazor app to a subfolder within the same shared output directory
      - name: Publish Blazor
        run: dotnet publish Georeach/Georeach.csproj -c Release -o deployment_output/blazor

      # Upload combined artifact for deployment
      - name: Upload deployment artifact
        uses: actions/upload-artifact@v3
        with:
          name: combined-app
          path: deployment_output

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download deployment artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: combined-app
          path: deployment_output

      # Deploy combined artifact to Azure Web App
      - name: Deploy combined app to Azure Web App
        id: deploy-app
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Georeach'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: deployment_output
